import type { ReactNode } from 'react';
import { Link } from 'react-router';
import { Wordmark } from '../ui/primitives';
import { st } from '../ui/st';

const H2 = 'font:700 22px var(--font-display);letter-spacing:-0.02em;margin:0';
const P = 'font:400 14.5px/1.6 var(--font-ui);color:var(--text2);margin:0;text-wrap:pretty';
const LI = 'font:400 14.5px/1.55 var(--font-ui);color:var(--text2)';

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section style={st('display:flex;flex-direction:column;gap:10px')}>
      <h2 style={st(H2)}>{title}</h2>
      {children}
    </section>
  );
}

function List({ items }: { items: ReactNode[] }) {
  return (
    <ul style={st('margin:0;padding-left:20px;display:flex;flex-direction:column;gap:6px')}>
      {items.map((item, i) => (
        <li key={i} style={st(LI)}>
          {item}
        </li>
      ))}
    </ul>
  );
}

/** `/privacy`: what QueueUp stores about you and what is and isn't encrypted. Reachable signed out
 * (linked from the login page) and from Settings. */
export function PrivacyPage({ signedIn }: { signedIn: boolean }) {
  return (
    <div style={st('min-height:100vh;background:var(--bg);color:var(--text)')}>
      <div style={st('max-width:760px;margin:0 auto;padding:0 clamp(16px,4vw,40px) 64px;display:flex;flex-direction:column;gap:32px')}>
        <div style={st('display:flex;align-items:center;gap:10px;height:68px')}>
          <Link to="/" style={st('flex:1;display:flex;text-decoration:none')}>
            <Wordmark size={23} />
          </Link>
          <Link to="/" style={st('height:40px;padding:0 18px;border-radius:999px;border:1px solid var(--line);color:var(--text);font:600 13.5px var(--font-ui);display:flex;align-items:center;text-decoration:none')}>
            {signedIn ? 'Back to QueueUp' : 'Sign in'}
          </Link>
        </div>

        <div style={st('display:flex;flex-direction:column;gap:10px')}>
          <h1 style={st('font:700 clamp(30px,6vw,44px)/1.05 var(--font-display);letter-spacing:-0.03em;margin:0')}>Privacy policy</h1>
          <p style={st(P)}>
            QueueUp is self-hosted software. The person or group running this server (the operator) controls the database it
            runs on and can access everything described below. This page describes what the software itself stores and protects;
            how the server is hosted, backed up and secured beyond that is up to the operator.
          </p>
        </div>

        <Section title="What we collect and save">
          <List
            items={[
              <>
                <b>Your account:</b> the identifier your sign-in provider gives us (Discord, Google, Steam or a custom OpenID
                provider), your email address, display name and avatar, the date you joined, and any extra sign-in methods you link.
                QueueUp never sees or stores a password; sign-in is handled by those providers.
              </>,
              <>
                <b>Your profile settings:</b> the systems you own, whether your public profile is on, an optional profile link name,
                your currency choice, and your friend code.
              </>,
              <>
                <b>Your library and activity:</b> the games on your Personal Shelf and in your rooms, their statuses, votes, reviews,
                tags, which games you own and on what platform, your play journal, and playtime and achievement progress when you
                connect Steam or Playnite.
              </>,
              <>
                <b>Social data:</b> friends and friend requests, room memberships and roles, room invite codes, and the activity feed
                and notifications generated by all of the above.
              </>,
              <>
                <b>Imports and keys:</b> your Steam ID if you link Steam, library data you import through Playnite, and the API keys
                you create (see below for how those are stored).
              </>,
              <>
                <b>Your session:</b> a cookie named <code>sq_session</code> keeps you signed in for up to 30 days. It is
                HTTP-only, and the session itself is kept on the server.
              </>,
              <>
                <b>Server logs:</b> the server may log requests (such as the page requested, the response and your IP address), depending
                on the operator's logging settings.
              </>,
            ]}
          />
          <p style={st(P)}>We do not run ads or analytics, and we do not sell your data.</p>
        </Section>

        <Section title="What is encrypted, and what isn't">
          <p style={st(P)}>
            <b>Protected by QueueUp:</b>
          </p>
          <List
            items={[
              <>
                <b>Integration credentials</b> an admin enters in Settings (for example API keys and the tunnel token) are encrypted at
                rest with AES-256-GCM, using a key derived from the server's <code>SESSION_SECRET</code>.
              </>,
              <>
                <b>Your API keys</b> are stored only as a one-way SHA-256 hash. The real key is shown once when you create it and can't
                be recovered afterwards.
              </>,
              <>
                Your <b>session cookie</b> is HTTP-only and marked Secure whenever the site is served over HTTPS.
              </>,
            ]}
          />
          <p style={st(P)}>
            <b>Not encrypted by QueueUp:</b>
          </p>
          <List
            items={[
              <>
                Everything else in the database is stored as ordinary readable data: your email, display name and avatar link, your
                library, reviews, votes, friends, notifications and activity. Anyone with access to the database, or a copy of it, can read
                it.
              </>,
              <>
                A room's <b>Discord webhook URL</b> is stored as plain text (only the Room Master can see it in the app).
              </>,
              <>
                <b>Sessions</b> are held in the server's Redis store unencrypted, and <b>database backups</b> contain all of the above;
                only the encrypted admin credentials stay encrypted inside them.
              </>,
              <>
                <b>Encryption in transit</b> (HTTPS) is not provided by QueueUp itself. It depends on the operator putting the server
                behind HTTPS, which they should always do. Disk-level encryption of the server is also the operator's responsibility.
              </>,
            ]}
          />
        </Section>

        <Section title="Who can see your data">
          <List
            items={[
              <>
                <b>Other members and the public:</b> room members see your display name and avatar, and what you add, vote on and
                review in shared rooms. Friends see your activity. If your public profile is on (it is by default), anyone with the link
                can see your name, avatar, systems, achievements, and the games on your shelf that aren't hidden. You can turn it off in
                Settings, and hide individual games. Your email address is not shown to other users or on your public profile.
              </>,
              <>
                <b>The operator and admins</b> can see accounts, including email addresses, and can access the database.
              </>,
            ]}
          />
        </Section>

        <Section title="Other services involved">
          <p style={st(P)}>To do its job the server talks to a few outside services, and some of your data is sent to them:</p>
          <List
            items={[
              'Your sign-in provider (Discord, Google, Steam or your organisation\'s OpenID provider) when you sign in or link an account.',
              'IGDB (via Twitch) for game details, Steam for library, wishlist and playtime data, and GG.deals for prices. These receive game titles and ids, and the Steam ID you link.',
              'Discord, only if a Room Master adds a webhook: room events are posted to that channel.',
              'Cloudflare Turnstile, if the operator turns on the sign-in security check; YouTube (privacy-enhanced mode) when you play a trailer; and Google Fonts for the typefaces.',
            ]}
          />
        </Section>

        <Section title="Your choices">
          <List
            items={[
              <>
                <b>Download my data</b> and <b>Delete my account</b> are both in Settings. Deleting your account removes your data from
                this server.
              </>,
              'You can revoke API keys, unlink sign-in methods, turn off your public profile and hide games at any time.',
              'To ask about anything else, contact the operator of this server.',
            ]}
          />
        </Section>
      </div>
    </div>
  );
}
